import type { Metadata } from "next";
import "@/styles/globals.css";

import { NuqsAdapter } from "nuqs/adapters/next/app";

import { BreakpointIndicator } from "@/components/dev/breakpoint-ind";
import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import { OpenPanelProvider } from "@/components/openpanel-provider";

import { acidGrotesk, mono, sfPro } from "@/assets/fonts";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(sfPro.className, mono.variable, acidGrotesk.variable, "antialiased")}>
        <OpenPanelProvider>
          <NuqsAdapter>
            <Navbar />
            {children}
            <Footer />
          </NuqsAdapter>
        </OpenPanelProvider>

        <BreakpointIndicator />

        {/* Live region for screen reader announcements */}
        <div aria-atomic="true" aria-live="polite" className="sr-only" id="live-region" />
      </body>
    </html>
  );
}
